-- Core catalog for Crispy Crave Next.js app (Postgres / Supabase).
-- Run this in the Supabase SQL Editor or via `supabase db push` if you use the CLI.

create table if not exists public.restaurants (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  logo text,
  delivery_time text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.menus (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants (id) on delete cascade,
  name text not null,
  description text,
  price numeric(10, 2) not null,
  image text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.restaurants enable row level security;
alter table public.menus enable row level security;

drop policy if exists "public_read_active_restaurants" on public.restaurants;
drop policy if exists "public_read_active_menus" on public.menus;

create policy "public_read_active_restaurants"
  on public.restaurants
  for select
  to anon, authenticated
  using (is_active = true);

create policy "public_read_active_menus"
  on public.menus
  for select
  to anon, authenticated
  using (
    is_active = true
    and exists (
      select 1
      from public.restaurants r
      where r.id = menus.restaurant_id
        and r.is_active = true
    )
  );

-- Optional seed (matches legacy chicken_ordering.sql sample shops / menus)
insert into public.restaurants (id, name, description, logo, delivery_time, is_active)
values
  (
    1,
    'Crispy King',
    'Crispy King is a fast-food business, specializing in fried chicken.',
    'ck.png',
    '10-15',
    true
  ),
  (
    3,
    'Krazy Crunch',
    'Filipino fast-food chain known for affordable, crunchy fried chicken.',
    'shop_69462b57326096.76403290.jpg',
    '10-20',
    true
  )
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.restaurants', 'id'),
  (select coalesce(max(id), 1) from public.restaurants)
);

insert into public.menus (
  id, restaurant_id, name, description, price, image, is_active
)
values
  (11, 1, 'Bola-bola', 'Skewered savory meatballs — great with rice.', 10.00, 'crispy_king/bola_bola.jpg', true),
  (12, 1, 'Ngohiong', 'Crispy Cebu-style roll with spiced filling.', 12.00, 'crispy_king/ngohiong.jpg', true),
  (13, 1, 'Siomai', 'Steamed dumplings, hot and juicy.', 30.00, 'crispy_king/siomai.jpg', true),
  (14, 1, 'Lumpia', 'Golden fried spring rolls.', 8.00, 'crispy_king/lumpia.jpg', true),
  (15, 1, 'Siopao', 'Fluffy steamed bun with savory filling.', 30.00, 'crispy_king/siopao.jpg', true),
  (16, 1, 'Fried Chicken', 'Chicken that is crunchy on the outside and juicy on the inside.', 50.00, 'crispy_king/chicken.jpg', true),
  (17, 1, 'Fried Chicken with rice', 'Crispy fried chicken with steamed rice.', 60.00, 'crispy_king/fried_chicken with rice.jpg', true),
  (21, 3, 'Beef pares', 'Slow-cooked beef in savory broth — no rice.', 55.00, 'crazy_krunch/beef_pares.jpg', true),
  (22, 3, 'Beef pares with rice', 'Beef pares with steamed rice.', 65.00, 'crazy_krunch/beef_pares with rice.jpg', true),
  (23, 3, 'Chicken', 'Crispy chicken serving — no rice.', 50.00, 'crazy_krunch/fried_chicken.jpg', true),
  (24, 3, 'Chicken with rice', 'Crispy chicken with steamed rice.', 60.00, 'crazy_krunch/fried_chicken with rice.jpg', true),
  (25, 3, 'Lumpia (3 pcs)', 'Three pieces of crispy lumpia.', 25.00, 'crazy_krunch/lumpia 3pcs.jpg', true),
  (26, 3, 'Siomai (3 pcs)', 'Three pieces of steamed siomai.', 25.00, 'crazy_krunch/siomai 3 pcs.jpg', true),
  (27, 3, 'Kikiam', 'Street-style kikiam, fried to order.', 20.00, 'crazy_krunch/kikiam.jpg', true),
  (28, 3, 'Cheese sticks', 'Melty cheese sticks, golden fried.', 20.00, 'crazy_krunch/cheese_sticks.jpg', true),
  (29, 3, 'Tempura', 'Light, crispy tempura.', 20.00, 'crazy_krunch/tempura.jpg', true),
  (30, 3, 'Fries', 'Hot, seasoned fries.', 20.00, 'crazy_krunch/fries.jpg', true),
  (31, 3, 'Nuts', 'Crunchy snack nuts.', 10.00, 'crazy_krunch/nuts.jpg', true)
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.menus', 'id'),
  (select coalesce(max(id), 1) from public.menus)
);
